development: &defaults
  helpers: 
    :fb_name: 
      :description: Renders the name of the user specified, optionally linked to his or her profile.
      :wiki_url: http://wiki.developers.facebook.com/index.php/Fb:name
    :fb_profile_pic: 
      :description: Turns into an img tag for the specified user's or Facebook Page's profile picture.
      :wiki_url: http://wiki.developers.facebook.com/index.php/Fb:profile-pic

test:
  <<: *defaults
production:
  <<: *defaults
