development: &defaults
  helpers: 
    :fb_name: 
      :description: Renders the name of the user specified, optionally linked to his or her profile.
      :wiki_url: http://wiki.developers.facebook.com/index.php/Fb:name
    :fb_profile_pic: 
      :description: Turns into an img tag for the specified user's or Facebook Page's profile picture.
      :wiki_url: http://wiki.developers.facebook.com/index.php/Fb:profile-pic
    :fb_login_button: 
      :description: Renders a Facebook Connect login button image on your site.
      :wiki_url: http://wiki.developers.facebook.com/index.php/Fb:login-button
    :fb_login_and_redirect: 
      :description: Renders a Facebook Connect login button image on your site.
      :wiki_url: http://wiki.developers.facebook.com/index.php/Fb:login-button
      :not_in_fb: true
    :fb_logout_link: 
      :description: Log user out from this session and Facebook, then redirect to the specified url.
      :wiki_url: http://wiki.developers.facebook.com/index.php/JS_API_M_FB.Connect.LogoutAndRedirect
      :not_in_fb: true


test:
  <<: *defaults
production:
  <<: *defaults
